id = "faded-prism-theme"
name = "Faded Prism Theme"
version = "1.4.1"
schema_version = 1
authors = ["Ryan Brue <ryanbrue.dev@gmail.com>"]
description = "A faint pastel theme for Zed"
repository = "https://github.com/ryanabx/faded-prism-zed"
